[package]
name = "clusia-tray"
description = "Clúsia menu bar tray"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
clusia-core.workspace = true
clusia-protocol.workspace = true
tracing.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
