#!/usr/bin/env python3
"""Writes crates/clusia-app/src/ui/emoji/table.rs from emojibase-data and the vendored Twemoji PNGs.

    scripts/gen-emoji-table.py --emojibase <emojibase-data package dir> [--png DIR] [--out FILE]

Standard library only. The output is committed; run this again only to move to a newer emojibase
or Twemoji release.
"""
import argparse
import json
import os
import sys

GROUPS = [
    "SmileysEmotion",
    "PeopleBody",
    "Component",
    "AnimalsNature",
    "FoodDrink",
    "TravelPlaces",
    "Activities",
    "Objects",
    "Symbols",
    "Flags",
]


def twemoji_name(s):
    """Twemoji's file stem: lowercase code points joined by '-', FE0F kept only with a ZWJ."""
    keep = "\u200d" in s
    return "-".join(f"{ord(c):x}" for c in s if keep or c != "\ufe0f")


def lit(s):
    """A Rust string literal with every non-ASCII character escaped."""
    out = []
    for c in s:
        if c in '"\\':
            out.append("\\" + c)
        elif 0x20 <= ord(c) < 0x7F:
            out.append(c)
        else:
            out.append("\\u{%x}" % ord(c))
    return '"' + "".join(out) + '"'


def strs(items):
    return "&[" + ", ".join(lit(i) for i in items) + "]"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    ap = argparse.ArgumentParser()
    ap.add_argument("--emojibase", required=True)
    ap.add_argument("--png", default=os.path.join(root, "crates/clusia-app/assets/emoji/72x72"))
    ap.add_argument("--out", default=os.path.join(root, "crates/clusia-app/src/ui/emoji/table.rs"))
    args = ap.parse_args()

    with open(os.path.join(args.emojibase, "en/compact.json"), encoding="utf-8") as f:
        compact = json.load(f)
    with open(os.path.join(args.emojibase, "en/shortcodes/github.json"), encoding="utf-8") as f:
        github = json.load(f)
    with open(os.path.join(args.emojibase, "en/data.json"), encoding="utf-8") as f:
        data = json.load(f)
    # Single characters that read as text unless U+FE0F follows (©, ™, ❤): emojibase type 0.
    text_style = sorted(
        {e["emoji"].replace("\ufe0f", "") for e in data if e["type"] == 0 and len(e["emoji"].replace("\ufe0f", "")) == 1}
    )
    pngs = sorted(n for n in os.listdir(args.png) if n.endswith(".png"))
    have = set(pngs)

    rows = []
    for e in sorted((e for e in compact if "group" in e), key=lambda e: e["order"]):
        emoji = e["unicode"]
        name = twemoji_name(emoji)
        if name + ".png" not in have:
            name = emoji.replace("\ufe0f", "")
            name = "-".join(f"{ord(c):x}" for c in name)
        if name + ".png" not in have:
            sys.exit(f"no Twemoji file for {e['hexcode']} {e['label']}")
        codes = github.get(e["hexcode"], [])
        if isinstance(codes, str):
            codes = [codes]
        rows.append((emoji, name + ".png", e["label"], GROUPS[e["group"]], e.get("tags", []), codes))

    lines = [
        "//! Generated by `scripts/gen-emoji-table.py` from emojibase-data 17.0.0 (MIT) and the vendored",
        "//! Twemoji 72x72 PNGs (CC-BY 4.0). Do not edit by hand.",
        "",
        "use super::{EmojiEntry, Group};",
        "",
        "#[rustfmt::skip]",
        "pub static EMOJI: &[EmojiEntry] = &[",
    ]
    for emoji, file, label, group, tags, codes in rows:
        lines.append(
            f"    EmojiEntry {{ emoji: {lit(emoji)}, file: {lit(file)}, label: {lit(label)}, "
            f"group: Group::{group}, tags: {strs(tags)}, shortcodes: {strs(codes)} }},"
        )
    lines += ["];", "", "/// Characters that stay text unless U+FE0F follows them.", "#[rustfmt::skip]", "pub static TEXT_STYLE: &[char] = &["]
    lines += ["    " + ", ".join("'" + ("\\u{%x}" % ord(c)) + "'" for c in text_style) + ","]
    lines += ["];", "", "#[rustfmt::skip]", "pub static PNGS: &[(&str, &[u8])] = &["]
    for n in pngs:
        lines.append(f'    ("{n}", include_bytes!("../../../assets/emoji/72x72/{n}")),')
    lines += ["];", ""]
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(rows)} emoji, {len(pngs)} images -> {args.out}")


if __name__ == "__main__":
    main()
